export const UPDATE_APP_STATUS = 'UPDATE_APP_STATUS';
export const UPDATE_APP_DIFFICULTY = 'UPDATE_APP_DIFFICULTY';
export const UPDATE_APP_SCORE = 'UPDATE_APP_SCORE';
export const UPDATE_APP_TIME = 'UPDATE_APP_TIME';
export const UPDATE_APP_DEFAULT_TIME = 'UPDATE_APP_DEFAULT_TIME';

export const UPDATE_STATISTICS_COUNT_OF_CORRECT_ANSWERS = 'UPDATE_STATISTICS_COUNT_OF_CORRECT_ANSWERS';
export const UPDATE_STATISTICS_COUNT_OF_TESTS = 'UPDATE_STATISTICS_COUNT_OF_TESTS';
export const UPDATE_STATISTICS_DIFFICULTY = 'UPDATE_STATISTICS_DIFFICULTY';
export const UPDATE_STATISTICS_END_GAME_DATE_TIME = 'UPDATE_STATISTICS_END_GAME_DATE_TIME';
export const UPDATE_STATISTICS_SOLVING_TIME = 'UPDATE_STATISTICS_SOLVING_TIME';
